export const bodyParts = [
  { name: "adductors", value: "Adductors" },
  { name: "biceps", value: "Biceps" },
  { name: "calves", value: "Calves" },
  { name: "chest", value: "Chest" },
  { name: "forearms", value: "Forearms" },
  { name: "glutes", value: "Glutes" },
  { name: "hamstrings", value: "Hamstrings" },
  { name: "lats", value: "Lats" },
  { name: "lower_back", value: "Lower back" },
  { name: "middle_back", value: "Middle back" },
  { name: "neck", value: "Neck" },
  { name: "quadriceps", value: "Quads" },
  { name: "traps", value: "Traps" },
  { name: "triceps", value: "Triceps" },
];
